### ISSUE TITLE
Linux native Java (?), command-line friendly

### ISSUE THREAD

**Issue by EeVee0** [Rash-in/StarParseLinux#1]
First,  OH THANK YOU GREAT CHAMPION!!

Not really an issue, though offers another way to do it.

### Part 2: install different Java

- [java.com](https://java.com/en/download/manual.jsp)
- choose "Linux x64" download

```
$ sudo -i
# mkdir /opt/java
# cd /opt/java
# mv /home/user/Downloads/jre* .
# tar zxvf jre...
```

### Part 4: less angry

```
$ cd ~/.StarParse/app
$ /opt/java/jre1.8.0.311/bin/java -jar starparse-launcher.jar
```

Updates (green text), then expected error "Launching client: Failed" (red text).

### Part 5: launching

Shell script:

```
$ cat starparse1.sh
#!/bin/bash

cd "/home/$USER/.StarParse/dosdevices/c:/users/user/Local Settings/Application Data/StarParse/app/client/app"
/opt/java/jre1.8.0_311/bin/java -jar starparse-client.jar
```

**Comment by Rash-in** [comment]
Thanks for the info. I am totally trying this tomorrow and see how it goes. I think I gave up way to early with native java. or was looking too hard inside the app to figure it out.

**Comment by Rash-in** [comment]
Moved in all the changes :D. confirmed that it works splendidly with 7.0......so far.lol.
