### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by r-vd-woude** [Rash-in/StarParseLinux#6]
Maybe add a section in which you change the permission to be able to write config file. Otherwise, you would need to configure StarParse every time it starts.

Related to this, StarParse does not seem to remember locations for the overlays, not sure why.

**Comment by Rash-in** [comment]
I guess I am not following for the first part. I am able to write to the config file and have started the app at least 50 times and it is retaining all my settings. 

I know about the overlays issue, Not too sure that they are the same thing though. I am still looking into it.

Do you have any java logs that is stating you aren't able to write to the config?

**Comment by Rash-in** [comment]
I am going to go ahead and close this down. I haven't seen any issues writing to the config file. I can re-open the issue if you are still having trouble or need some help with it.
