### ISSUE TITLE
How to get overlay working

### ISSUE THREAD

**Issue by r-vd-woude** [Rash-in/StarParseLinux#9]
Thanks for the great tutorial!

I'm using KDE Plasma, and to get the overlays working you can add window rules to keep SW:TOR in the background always. In this way, the overlays created by StarParse will always be on top. Only problem is, taskbar will remain visible. I solved this by using the following widget: https://github.com/Intika-KDE-Plasmoids/plasmoid-toggle-panel. This way you can hide the panel and keep the StarParse overlays on top. 

Nice solution, but will only work on KDE.

![starwars_bottom](https://user-images.githubusercontent.com/20134124/158696447-2555dba3-a13a-4bb4-b568-58ed28972c47.png)
![starparse_top](https://user-images.githubusercontent.com/20134124/158696451-6bba79d4-d8a1-48d8-85d4-274f33ec6ce3.png)
![Screenshot_20220312_213815](https://user-images.githubusercontent.com/20134124/158696453-439a77f5-9f71-4cd3-8d18-a585c129c1d5.png)

**Comment by Rash-in** [comment]
Thanks for the info. That gets a couple of research leads pumping at least. like gconf editor or gnome window manager plugins to look into.

side question for you. Does that work with Healer HoTs as well?

**Comment by Rash-in** [comment]
LOL. Found the no plugin, no 3rd party solution.      Smacked me right in the face when I saw it.

https://www.makeuseof.com/keep-a-window-always-on-top-linux/#:~:text=To%20use%20this%20method%2C%20open,mode%2C%20follow%20the%20same%20steps.

Select overlay window:  alt + space -> select always on top

also works for raid HoTs. Just tested.

Adding to instructions.

**Comment by r-vd-woude** [comment]
That's a nice solution, unfortunately not working for those of use who use tiling WM's or something other than Gnome:). Still, nice thing to add.
